version: "3"

services:
  hello:
    build:
      context: ./hello
    image: seanly/imgutils:feature-hello-v1.0
  world:
    build:
      context: ./world
    image: seanly/imgutils:feature-world-v1.0
