version: "3"

services:
  base:
    build:
      context: ./base
    image: seanly/feature-images:features-base-v1.0
  world:
    build:
      context: ./world
    image: seanly/feature-images:features-world-v1.0
